server:
  port: 8081
spring:
  application:
    name: spring-flight-consumer
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: flight-info-streams-consumer-app
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.springframework.kafka.support.serializer.JsonSerde
